#pragma once 

#include <cstdint>

enum class PacketType : uint32_t {
	AUTHORIZE,
	GET_FRIEND_INFO,
	CREATE_CALL,
	END_CALL,
	CALL_ACCEPTED,
	CALL_DECLINED,
	VOICE,
	AUTHORIZATION_SUCCESS,
	AUTHORIZATION_FAIL,
	FRIEND_INFO_SUCCESS,
	FRIEND_INFO_FAIL,
	INCOMING_CALL
};
