services:
  calliforniaServer:
    image: ${DOCKERHUB_NAMESPACE}/callifornia-server:${IMAGE_TAG}
    build:
      context: .
      dockerfile: calliforniaServer.Dockerfile
    ports:
      - "8081:8081/tcp"
      - "8081:8081/udp"
    volumes:
      - ./volumes/calliforniaServer/logs:/app/logs
    restart: unless-stopped

  serverUpdater:
    image: ${DOCKERHUB_NAMESPACE}/callifornia-server-updater:${IMAGE_TAG}
    build:
      context: .
      dockerfile: calliforniaServerUpdater.Dockerfile
    ports:
      - "8082:8082/tcp"
    volumes:
      - ./volumes/serverUpdater/logs:/app/logs
      - ./volumes/serverUpdater/versions:/app/versions
    restart: unless-stopped