#pragma once 

#include <cstdint>

enum class PacketType : uint32_t {
	// only receive
	AUTHORIZE,
	LOGOUT,
	GET_FRIEND_INFO,

	// receive and redirect
	START_SCREEN_SHARING,
	STOP_SCREEN_SHARING,
	SCREEN,
	START_CALLING,
	END_CALL,
	STOP_CALLING,
	CALL_ACCEPTED,
	CALL_DECLINED,
	END_CALL_OK,
	STOP_CALLING_OK,
	CALL_ACCEPTED_OK,
	CALL_DECLINED_OK,
	START_CALLING_OK,
	START_SCREEN_SHARING_OK,
	STOP_SCREEN_SHARING_OK,
	START_SCREEN_SHARING_FAIL,

	// confirmations only send
	AUTHORIZE_SUCCESS,
	AUTHORIZE_FAIL,
	GET_FRIEND_INFO_SUCCESS,
	GET_FRIEND_INFO_FAIL,
	CALL_ACCEPTED_FAIL,
	START_CALLING_FAIL,
	LOGOUT_OK,

	// special packets
	VOICE,
	PING,
	PING_SUCCESS
};