#pragma once 

#include <cstdint>

enum class PacketType : uint32_t {
	AUTHORIZE,
	LOGOUT,
	GET_FRIEND_INFO,
	CREATE_CALL,
	CREATE_GROUP_CALL,
	END_CALL,
	END_GROUP_CALL,
	JOIN_REQUEST,
	JOIN_REQUEST_CANCELED_BY_REQUESTER,
	JOIN_ALLOWED,
	GROUP_CALL_NEW_PARTICIPANT,
	JOIN_DECLINED,
	LEAVE_GROUP_CALL,
	GROUP_CALL_PARTICIPANT_QUIT,
	GROUP_CALL_NOT_EXIST,
	CALL_ACCEPTED,
	CALL_DECLINED,
	CALLING_END,
	VOICE,
	PING,
	PING_SUCCESS,
	AUTHORIZATION_SUCCESS,
	AUTHORIZATION_FAIL,
	FRIEND_INFO_SUCCESS,
	CREATE_GROUP_CALL_SUCCESS,
	CREATE_GROUP_CALL_FAIL,
	FRIEND_INFO_FAIL,
	INCOMING_CALL
};
